blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }
    requirements:
        _method:  GET
blog_about:
    path:     /about
    defaults: { _controller: BlogBundle:Default:about }
    requirements:
        _method:  GET
blog_show:
    path:     /{id}
    defaults: { _controller: BlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+
